import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hemant Bhatt | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 1. Add suppressHydrationWarning here to fix the <html> error
    <html lang="en" suppressHydrationWarning>
      
      {/* 2. Add suppressHydrationWarning here to fix the <body> error (Grammarly) */}
      <body 
        className={inter.className}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}